server:
  port: 8087
  
logging:
  level:
    org.springframework : error
    com.techtalk.debu: debug
spring:
  application:
    name: job-scheduler
  scheduler:
   pool: 
    size: 4
      
 
 
